HW2 is completed
desl90/otus-golang pull request #3
Opened 2022-12-13 16:41 UTC by desl90

## Домашнее задание №2 «Распаковка строки»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [x] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [x] Я запустил `go mod tidy`.
- [x] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [x] Я сравнил объем кода с объемом авторского решения. [Зачем сверять объем кода?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D1%81%D0%B2%D0%B5%D1%80%D1%8F%D1%82%D1%8C-%D0%BE%D0%B1%D1%8A%D0%B5%D0%BC-%D0%BA%D0%BE%D0%B4%D0%B0)
  - unpack.go ~45 строк для задания без звездочки
  - unpack.go ~75 строк для задания со звездочкой

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты - до 4 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2022-12-15 03:09 UTC, Nikscorp requested changes
Александр, добрый день!
Спасибо за проделанную работу.

Поправьте пока замечания, указанные в PR, у вас не совсем верно оформлена работа.
После этого присылайте еще раз и тогда уже посмотрю логику unpack-а.

2022-12-15 03:09 UTC, Nikscorp commented on hw02_unpack_string/unpacker/unpack.go
> +package unpacker
WARN: особого смысла выделять отдельный пакет для функционала простых ДЗ нет.

2022-12-15 03:09 UTC, Nikscorp commented on hw02_unpack_string/main.go
> +func main() {
WARN: зачем вам тут main? вы пишите функцию и тестируете ее, main тут лишний от слова совсем

2022-12-16 12:59 UTC, desl90 commented on hw02_unpack_string/unpacker/unpack.go
> +package unpacker
исправил

2022-12-16 13:02 UTC, desl90 commented on hw02_unpack_string/main.go
> +func main() {
Вынес, чтобы протестировать через go run.

Пример: go run unpack.go
Ответ: "package command-line-arguments is not a main package"

Как запускать и тестировать пакеты без main?

2022-12-16 13:02 UTC, desl90 commented on hw02_unpack_string/main.go
> +func main() {
Исправил

2022-12-18 19:47 UTC, Nikscorp approved these changes
Александр, добрый день!

Хорошая работа, код лаконичен.
Оставил несколько замечаний в комментариях к PR.

Текущая оценка 7 баллов из 10.
Работа принята.

> **P.S.**
> 
> Нотация:
> 
> - CRIT: критическое замечание ведущее к значительному снижению баллов
> - WARN: некритическое замечание ведущее к незначительному снижению баллов (часто по критерию чистого кода / аккуратности)
> - NB: nota bene — что-то на что нужно обратить внимание (например в реальных проектах), совет, к снижению баллов не ведет
> - GREAT: часть проекта, которую хочется похвалить, выделить
> 
> Проверяющие тоже люди — в своих замечаниях я могу что-то упустить или ошибиться, в случае если вы не согласны с замечаниями — не стесняйтесь их оспаривать.
> 
> Если что-то нужно перепроверить, заапрувить, принять инвайт, поднять оценку, то прошу следовать данной последовательности:
> 
> 1. Написать в чате со мной с ДЗ на сайте ОТУС-а и перекинуть ДЗ на меня со статусом "Нужно проверить"
> 2. Написать на GitHub-е
> 3. Продублировать мне сообщение в корпоративном Slack-е: (Nikita Voynov)

2022-12-18 19:47 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\4\5`, expected: `qwe45`},
WARN: нет тестов на не-ascii символы

2022-12-18 19:47 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case unicode.IsDigit(letter) && !isExcluded:
Использование `unicode.IsDigit`. Несмотря на то, что в задании указана рекомендация по использованию данной функции я советовал бы отнестись к ней с осторожностью. Помимо арабских цифр `0, 1 ... 9` она трактует как цифры также иные символы, например отсюда https://www.fileformat.info/info/unicode/category/Nd/list.htm . Если вы трактуете задание таким образом, то необходимо покрыть данный функционал юнит-тестами, также прошу учесть, что с такой трактовкой ваш код также не будет работать, так как digit-символы вне `0...9` не смогут привестись к int с помощью `strconv.Atoi`, пример: https://go.dev/play/p/zPCRUQsqPuG. Я обсужу с руководителем курса рекомендацию по использованию `unicode.IsDigit`. Я рекомендую проверять символы простым сравнением с байтами `0` и `9`, а к инту приводить простым вычитанием из символа `'0'` с расширением типа

2022-12-18 19:47 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	return unicode.IsLetter(letter) || isEscapedLetter(letter)
WARN: не знаю зачем вам этот `unicode.IsLetter` я вот даже не представляю на какой набор тимолов он ответит `true`. Достаточно проверить символ только на цифру и слэш, лучше не использовать функции, которые не понимаете.

Возможно поэтому (я не разбирался) строка вроде `*4bc2d5e` распознается как ошибочная

2022-12-19 16:22 UTC, desl90 commented on hw02_unpack_string/unpack.go
> +		case unicode.IsDigit(letter) && !isExcluded:
Понял, спасибо за глубокое пояснение! Да в ТЗ действительно рекомендуется использовать именно данные функции.

2022-12-19 16:25 UTC, desl90 commented on hw02_unpack_string/unpack.go
> +	return unicode.IsLetter(letter) || isEscapedLetter(letter)
Видимо я сделал слишком строгую валидацию входных данных. В данном случае isValidEscapeLetter - действительно создан для того, чтобы  строки вида *4bc2d5e распознавать как ошибочные. Тут с моей стороны нужно было явно показать это через тесты.

2022-12-19 16:30 UTC, merged

2022-12-19 16:51 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +		case unicode.IsDigit(letter) && !isExcluded:
да, уже поправили это из ТЗ

2022-12-19 16:52 UTC, Nikscorp commented on hw02_unpack_string/unpack.go
> +	return unicode.IsLetter(letter) || isEscapedLetter(letter)
нуу допустимо, конечно но вообще в ТЗ ничего не сказано о возможности сужения области значения — на вход подается произвольная строка :)

2022-12-19 16:54 UTC, desl90 commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\4\5`, expected: `qwe45`},
Это стандартный тест, который уже был перед выполнением ДЗ

2022-12-19 17:12 UTC, Nikscorp commented on hw02_unpack_string/unpack_test.go
> +		{input: `qwe\4\5`, expected: `qwe45`},
ну да, все так, но одним из ваших заданий является написание тестов. Я не увидел тесткейсов содержащих строки с не-ascii символами.